CREATE DATABASE prontuario;

USE prontuario;
/* Lógico_2: */

CREATE TABLE pacientes (
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    CPF VARCHAR(15) NOT NULL,
    DT_NASCIMENTO DATE,
    ESTADO_CIVIL varchar(50),
    CONJUGE varchar(50),
    ENDERECO varchar(60),
    BAIRRO varchar(50),
    CIDADE varchar(50),
    CEP varchar(50),
    UF char(2),
    FONE varchar(25),
    EMAIL varchar(50),
    PROFISSAO varchar(50),
    OBITO char(1) NOT NULL,
    OBS VARCHAR(100)
);

CREATE TABLE funcionarios (
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    MATRICULA VARCHAR(20) NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    CPF VARCHAR(20) NOT NULL,
    SENHA VARCHAR(200) NOT NULL,
    DT_NASCIMENTO DATE,
    FUNCAO VARCHAR(50),
    ATIVO char(1) NOT NULL,
    PERMISSAO INT NOT NULL
);

CREATE TABLE medicos (
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    CRM varchar(20) NOT NULL,
    ESPECIALIDADE VARCHAR(50) NOT NULL,
    FUNCIONARIO_ID INT NOT NULL,
    FOREIGN KEY (FUNCIONARIO_ID) REFERENCES funcionarios(ID)
);

CREATE TABLE consultas (
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    SINTOMAS VARCHAR(300) NOT NULL,
    OBSERVACOES VARCHAR(100),
    DATA_HORA DATE NOT NULL,
    PACIENTE_ID INT NOT NULL,
    MEDICO_ID INT NOT NULL,
    FOREIGN KEY (PACIENTE_ID) REFERENCES pacientes(ID),
    FOREIGN KEY (MEDICO_ID) REFERENCES medicos(ID)
);

CREATE TABLE perguntas (
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    DESCRICAO VARCHAR(80) NOT NULL,
    TIPO INT NOT NULL,
    QUESTIONARIO CHAR NOT NULL
);

CREATE TABLE respostas (
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    CONTEUDO VARCHAR(50) NOT NULL,
    PERGUNTA_ID INT NOT NULL,
    PACIENTE_ID INT NOT NULL,
    FOREIGN KEY (PERGUNTA_ID) REFERENCES perguntas(ID),
    FOREIGN KEY (PACIENTE_ID) REFERENCES pacientes(ID)
);

CREATE TABLE procedimentos (
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    TIPO VARCHAR(30) NOT NULL,
    DESCRICAO VARCHAR(80) NOT NULL,
    DATA_HORA DATETIME NOT NULL,
    CONSULTA_ID INT NOT NULL,
    FOREIGN KEY (CONSULTA_ID) REFERENCES consultas(ID)
);
