CREATE DATABASE prontuario;

USE prontuario;
/* Lógico_2: */

CREATE TABLE paciente (
    ID INT PRIMARY KEY,
    NOME VARCHAR(50),
    CPF VARCHAR(15),
    SENHA VARCHAR(200),
    DT_NASCIMENTO DATE,
    ALTURA DOUBLE,
    PESO DOUBLE,
    OBS VARCHAR(100)
);

CREATE TABLE funcionario (
    ID INT PRIMARY KEY,
    MATRICULA VARCHAR(20),
    NOME VARCHAR(50),
    CPF VARCHAR(20),
    SENHA VARCHAR(200),
    DT_NASCIMENTO DATE,
    FUNCAO VARCHAR(50)
);

CREATE TABLE consulta (
    ID INT PRIMARY KEY,
    SINTOMAS VARCHAR(300),
    OBSERVACOES VARCHAR(100),
    DATA_HORA DATE,
    PACIENTE_ID INT,
    SAUDE_ID INT
);

CREATE TABLE saude (
    ID INT PRIMARY KEY,
    NOME VARCHAR(50),
    CPF VARCHAR(20),
    SENHA VARCHAR(200),
    DT_NASCIMENTO DATE,
    ESPECIALIDADE VARCHAR(50)
);

CREATE TABLE perguntas (
    ID INT PRIMARY KEY,
    DESCRICAO VARCHAR(80),
    TIPO INT,
    QUESTIONARIO CHAR
);

CREATE TABLE respostas (
    ID INT PRIMARY KEY,
    CONTEUDO VARCHAR(50),
    PERGUNTA_ID INT,
    PACIENTE_ID INT
);

CREATE TABLE procedimentos (
    ID INT PRIMARY KEY,
    TIPO VARCHAR(30),
    DESCRICAO VARCHAR(80),
    DATA_HORA DATETIME,
    CONSULTA_ID INT
);
 
ALTER TABLE consulta ADD CONSTRAINT FK_consulta_2
    FOREIGN KEY (PACIENTE_ID)
    REFERENCES paciente (ID)
    ON DELETE SET NULL;
 
ALTER TABLE consulta ADD CONSTRAINT FK_consulta_3
    FOREIGN KEY (SAUDE_ID)
    REFERENCES saude (ID);
 
ALTER TABLE saude ADD CONSTRAINT FK_saude_2
    FOREIGN KEY (fk_consulta_ID)
    REFERENCES consulta (ID)
    ON DELETE SET NULL;
 
ALTER TABLE respostas ADD CONSTRAINT FK_respostas_2
    FOREIGN KEY (PERGUNTA_ID)
    REFERENCES perguntas (ID)
    ON DELETE SET NULL;
 
ALTER TABLE respostas ADD CONSTRAINT FK_respostas_3
    FOREIGN KEY (PACIENTE_ID)
    REFERENCES paciente (ID)
    ON DELETE SET NULL;
 
ALTER TABLE procedimentos ADD CONSTRAINT FK_procedimentos_1
    FOREIGN KEY (CONSULTA_ID)
    REFERENCES consulta (ID);
