CREATE DATABASE prontuario;

USE prontuario;
/* Lógico_2: */

CREATE TABLE pacientes (
    ID INT PRIMARY KEY,
    NOME VARCHAR(50),
    CPF VARCHAR(15),
    DT_NASCIMENTO DATE,
    ESTADO_CIVIL varchar(50),
    CONJUGE varchar(50),
    ENDERECO varchar(60),
    BAIRRO varchar(50),
    CIDADE varchar(50),
    CEP varchar(50),
    UF char(2),
    FONE varchar(25),
    EMAIL varchar(50),
    PROFISSAO varchar(50),
    OBITO char(1),
    OBS VARCHAR(100)
);

CREATE TABLE funcionarios (
    ID INT PRIMARY KEY,
    MATRICULA VARCHAR(20),
    NOME VARCHAR(50),
    CPF VARCHAR(20),
    SENHA VARCHAR(200),
    DT_NASCIMENTO DATE,
    FUNCAO VARCHAR(50),
    ATIVO char(1),
    PERMISSAO INT
);

CREATE TABLE consultas (
    ID INT PRIMARY KEY,
    SINTOMAS VARCHAR(300),
    OBSERVACOES VARCHAR(100),
    DATA_HORA DATE,
    PACIENTE_ID INT,
    MEDICO_ID INT
);

CREATE TABLE medicos (
    ID INT PRIMARY KEY,
    CRM varchar(20),
    NOME VARCHAR(50),
    CPF VARCHAR(20),
    SENHA VARCHAR(200),
    DT_NASCIMENTO DATE,
    ESPECIALIDADE VARCHAR(50)
);

CREATE TABLE perguntas (
    ID INT PRIMARY KEY,
    DESCRICAO VARCHAR(80),
    TIPO INT,
    QUESTIONARIO CHAR
);

CREATE TABLE respostas (
    ID INT PRIMARY KEY,
    CONTEUDO VARCHAR(50),
    PERGUNTA_ID INT,
    PACIENTE_ID INT
);

CREATE TABLE procedimentos (
    ID INT PRIMARY KEY,
    TIPO VARCHAR(30),
    DESCRICAO VARCHAR(80),
    DATA_HORA DATETIME,
    CONSULTA_ID INT
);
 
ALTER TABLE consultas ADD CONSTRAINT FK_consulta_2
    FOREIGN KEY (PACIENTE_ID)
    REFERENCES pacientes (ID)
    ON DELETE SET NULL;
 
ALTER TABLE consultas ADD CONSTRAINT FK_consulta_3
    FOREIGN KEY (MEDICO_ID)
    REFERENCES medicos (ID);
 
ALTER TABLE medicos ADD CONSTRAINT FK_saude_2
    FOREIGN KEY (fk_consulta_ID)
    REFERENCES consultas (ID)
    ON DELETE SET NULL;
 
ALTER TABLE respostas ADD CONSTRAINT FK_respostas_2
    FOREIGN KEY (PERGUNTA_ID)
    REFERENCES perguntas (ID)
    ON DELETE SET NULL;
 
ALTER TABLE respostas ADD CONSTRAINT FK_respostas_3
    FOREIGN KEY (PACIENTE_ID)
    REFERENCES pacientes (ID)
    ON DELETE SET NULL;
 
ALTER TABLE procedimentos ADD CONSTRAINT FK_procedimentos_1
    FOREIGN KEY (CONSULTA_ID)
    REFERENCES consultas (ID);
